In [29]:

import numpy as np
from numpy import linalg as LA

In [30]:
B=np.array([[-0.75,-1.5,0.5],[3.25,2.5,0.5],[1.25,-2.5,-3.5],[-3.75,1.5,2.5]])
#b=[[-0.75,-1.5,.5],[3.25,2.5,.5],[1.25,-2.5,-3.5],[-3.75,1.5,2.5]]

In [31]:
# Question 3 (c)
print(B)
c=np.cov(B,rowvar=False)
print(c)
v,d = LA.eig(c)
print(v)


[[-0.75 -1.5   0.5 ]
 [ 3.25  2.5   0.5 ]
 [ 1.25 -2.5  -3.5 ]
 [-3.75  1.5   2.5 ]]
[[ 8.91666667  0.16666667 -4.16666667]
 [ 0.16666667  5.66666667  4.33333333]
 [-4.16666667  4.33333333  6.33333333]]
[ 0.49703343 12.97881887  7.44081437]


In [32]:
# Question 3 (d)
import sklearn.decomposition as skd
import numpy as np
X=B
pca = skd.PCA(n_components = 3)
skd.PCA.fit(pca,X)
#W1 = pca.components_
#W = W1.transpose()
Z = pca.transform(X)
print(pca.components_)

[[-0.65675377  0.3733234   0.65521304]
 [ 0.66122187  0.70283233  0.26232109]
 [ 0.36257431 -0.60552156  0.70843738]]


In [33]:
print(Z)

[[ 0.26018674 -1.41900435  0.99057029]
 [-0.87353472  4.03721245  0.01878129]
 [-4.04749635 -1.8486773  -0.51250906]
 [ 4.66084433 -0.7695308  -0.49684253]]
